<!DOCTYPE html>
<html lang="en">
<head>
<title>Open Sing Along Jam</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
.show-element { display: block; }
.hide-element { display: none; }
.is-hidden {display: none;}
</style>
<script>
function toggleVisibility() {
  var element = document.getElementById('chord-container');
  element.classList.toggle('is-hidden');
}
function toggleChords(element) {
    const chordContainer = element.nextElementSibling;
    if (chordContainer.classList.contains("hide-element")) {
        chordContainer.classList.remove("hide-element");
        chordContainer.classList.add("show-element");
    } else {
        chordContainer.classList.remove("show-element");
        chordContainer.classList.add("hide-element");
    }
}
</script>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">HOME</a>
    <a href="#band" class="w3-bar-item w3-button w3-padding-large w3-hide-small">INSTRUCTIONS</a>
    <a href="#tour" class="w3-bar-item w3-button w3-padding-large w3-hide-small">SHARE</a>
  </div>
</div>

<!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
<!-- <div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
  <a href="#band" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">BAND</a>
  <a href="#tour" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">TOUR</a>
  <a href="#contact" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">CONTACT</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large" onclick="myFunction()">MERCH</a>
</div> -->

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">


  <!-- The Band Section -->
  <!-- <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    <h2 class="w3-wide">Sing Along Jam</h2>
    <p class="w3-opacity"><i>We love music</i></p>
    <p class="w3-justify">Pick a song</p>
  </div> -->
